config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  root 'report#index'
  resources :report do 
    collection do 
      get 'profile' => 'report#user_profile'
    end
  end

end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :user
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

 	geocoded_by :address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reports
  devise :omniauthable, :omniauth_providers => [:facebook]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_action :authenticate_user!
end
#weed is tight

app/controllers/report_controller.rb
class ReportController < ApplicationController

	def index
		@reports = Report.all
		@report_last = Report.last
		@report_lat = @report_last.latitude
		@report_lon = @report_last.longitude
		@last_time = Report.last.created_at.strftime("%b%d %I:%M%p")
		@geojson = Array.new
		@reports.each do |report|
			if report.report_type == "Assault" || report.report_type == "Hate Crime" || report.report_type == "Shooting" || report.report_type == "Kidnapping" || report.report_type == "Sexual Assault" || report.report_type == "Stabbing" || report.report_type == "Homicide"
				@geojson << {
						type: 'Feature',
	            geometry: {
	              type: 'Point',
	              coordinates: [report.longitude, report.latitude]},
	            properties: {
	                title: report.report_type,
	                description: report.description,
	                address: report.address,
	              	time_when: report.created_at.strftime("%b %d | %I:%M%p"),
	                'marker-size': 'large',
	                'marker-color': '#F53333',
	                'marker-symbol': 'hospital'
	            }
				}
			elsif report.report_type == "Drug"|| report.report_type == "Harassment"|| report.report_type == "Stalking"
				@geojson << {
						type: 'Feature',
	            geometry: {
	              type: 'Point',
	              coordinates: [report.longitude, report.latitude]},
	            properties: {
	                title: report.report_type,
	                description: report.description,
	                address: report.address,
	                time_when: report.created_at.strftime("%b %d | %I:%M%p"),
	                'marker-size': 'large',
	                'marker-color': '#FFA347',
	                'marker-symbol': 'hospital'
	            }
				}
      else report.report_type == "Theft"|| report.report_type == "Arson"|| report.report_type == "Disorderly Conduct"|| report.report_type == "Vandalism"
      	@geojson << {
						type: 'Feature',
	            geometry: {
	              type: 'Point',
	              coordinates: [report.longitude, report.latitude]},
	            properties: {
	                title: report.report_type,
	                description: report.description,
	                address: report.address,
	                time_when: report.created_at.strftime("%b %d | %I:%M%p"),
	                'marker-size': 'large',
	                'marker-color': '#FFD738',
	                'marker-symbol': 'hospital'
	            }
				}
      end
		end
		respond_to do |format|
			format.html
			format.json { render json: @geojson }
		end

	end

	def user_profile
		@reports = current_user.reports
	end

	def create
		@report = current_user.reports.build(report_params)
		if @report.save
  			redirect_to root_path
	  	else
	  		render :new
	  	end
	end

	def new
		@report = current_user.reports.build
	end

	def edit
		@report = current_user.reports.find(params[:id])
	end

	def update
    	@report = current_user.reports.find(params[:id])
 
    	if @report.update(report_params)
      		redirect_to root_path
    	else
      		render :edit
    	end
	end
	
	private

	# Use strong_parameters for attribute whitelisting
	# Be sure to update your create() and update() controller methods.

	def report_params
  		params.require(:report).permit(:title, :time, :description, :address, :latitude, :longitude, :report_type)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/application/_navigation.html.erb
<div class="container">
  <ul id="gn-menu" class="gn-menu-main">
    <li class="gn-trigger">
      <a class="gn-icon gn-icon-menu"><span>Menu</span></a>
      <nav class="gn-menu-wrapper">
        <div class="gn-scroller">
          <ul class="gn-menu">
           <!-- <li class="gn-search-item">
              <input placeholder="Search" type="search" class="gn-search">
              <a class="gn-icon gn-icon-search"><span>Search</span></a>
            </li> -->
            <% if controller.controller_name == 'report' && controller.action_name == 'index' %>
              <% if user_signed_in? %>
                <li><a href="#about" class="gn-icon gn-icon-earth">Map</a></li>
                <li><a href="/report/profile" class="gn-icon gn-icon-cog">Profile</a></li>
                <li><a href="/report/new" class="gn-icon gn-icon-download">Create Report</a></li>
              <% end %>
              <li><a href="#service" class="gn-icon gn-icon-help">About</a></li>
              <li><a href="#contact" class="gn-icon gn-icon-archive">Contact</a></li>
            <% end %>
            <% if user_signed_in? && controller.action_name != 'index' %>
              <li><a href="/report#about" class="gn-icon gn-icon-earth">Map</a></li>
              <li><a href="/report/profile" class="gn-icon gn-icon-cog">Profile</a></li>
              <li><a href="/report/new" class="gn-icon gn-icon-download">Create Report</a></li>
              <li><a href="/report#service" class="gn-icon gn-icon-help">About</a></li>
              <li><a href="/report#contact" class="gn-icon gn-icon-archive">Contact</a></li>
            <% end %>
          </ul>
        </div>
        <!-- /gn-scroller -->
      </nav>
    </li>
    <li>
      <%= link_to (image_tag "samaritwebsize.png"), report_index_path %>
    </li>
    <% if user_signed_in? %>
      <div class = "logoutbutton">
        <%= link_to('Logout', destroy_user_session_path, :method => :delete, :style => "align :right") %>
      </div>
    <% end %>     
    <li>
        <% if user_signed_in? == false %>
          <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <%= f.email_field :email, placeholder: "Email", autofocus: true, class: 'navbar-signin-form' %>
            <%= f.password_field :password, placeholder: "Password", autocomplete: "off", class: 'navbar-signin-form' %>
            <%= f.check_box :remember_me, class: 'navbar-signin-form' %>
            <%= f.label :remember_me, class: 'navbar-signin-form' %>
            <b><%= f.submit 'Sign in', class: 'navbar-signin-form' %></b>
          <% end %>
        <% end %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <title>Samarit</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700' rel='stylesheet'>
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.4/mapbox.css' rel='stylesheet' />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   
  <%= csrf_meta_tags %>
  
<script>
  function startTime() {
    var today=new Date();
    var h=today.getHours();
    var m=today.getMinutes();
    var s=today.getSeconds();
    m = checkTime(m);
    s = checkTime(s);
    document.getElementById('txt').innerHTML = h+":"+m+":"+s;
    var t = setTimeout(function(){startTime()},500);
}

function checkTime(i) {
    if (i<10) {i = "0" + i};  // add zero in front of numbers < 10
    return i;
}
</script>
</head>
<body data-spy="scroll" onload="startTime()">
<%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>

<p class="navbar-text pull-right">

<% if alert %>
  <p class="alert alert-danger"><br><br><%= alert %></p>
<% end %>

<%= render 'navigation' %>

<%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/report/edit.html.erb
<section id="about" class="about-section text-center bg-gray">
	<div class="report-form">
	<%= simple_form_for [current_user, @report], url: report_path(@report) do |f| %>
	  <%= f.input :report_type, collection: ["Arson","Assault","Disorderly Conduct","Drug","Harassment","Hate Crime","Homicide","Kidnapping","Sexual Assault","Shooting","Stabbing","Stalking","Theft","Vandalism"] %>
	  <br>
	  <%= f.input :address, placeholder: "123 Street City, State" %>
	  <br>
	  <%= f.input :description, as: :text, placeholder: "Details here..." %>
	  <br>
	  <%= f.input :time, collection: ["Just Now","15 Minutes Ago","30 Minutes Ago","45 Minutes Ago","1 Hour Ago","> 1 Hour Ago"], label: "When", default: ["Just Now"] %>
	  <br>
	  <%= f.button :submit, class: "btn btn-skin scroll" %>
	  <br>
	<% end %>
	<br>
	<%= link_to "Back", report_index_path, class: "btn btn-skin scroll" %>
	</div>
</section>

app/views/report/index.html.erb
<!-- Section: intro -->
<section id="intro" class="intro">
  <div class="slogan">
    <h1>crowdsourced crime reporting <br><br> for your neighborhood<br><br></h1>
    <% if user_signed_in? == false %>
      <%= link_to "sign up", new_user_registration_path, :class => "btn btn-skin scroll" %>
    <% end %>
    <% if user_signed_in? == true %>
      <a href="#about" class="btn btn-skin scroll">live map</a> <br ><br >
    <% end %>
  </div>
</section>
<!-- /Section: intro -->
<!-- Section: about -->
<section id="about" class="about-section text-center bg-gray">
  <% if user_signed_in? == true %>
    <div class="row">

      <div class='sidebar'>
      <div id='listings' class='listings'>  <%= link_to 'Create Report', new_report_path, class: "btn-pos btn btn-skin scroll" %></div>
      </div>
      <script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css' rel='stylesheet' />
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/css/font-awesome.min.css' rel='stylesheet' />

<script src='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/leaflet.markercluster.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.css' rel='stylesheet' />
<link href='https://api.tiles.mapbox.com/mapbox.js/plugins/leaflet-markercluster/v0.4.0/MarkerCluster.Default.css' rel='stylesheet' />
      <div id='map' class='map'> </div>
        <script>
        L.mapbox.accessToken = 'pk.eyJ1IjoibWJpZ2dpbnMiLCJhIjoiMTdiMjNiZDIzNmRkZWQzNGFkYmM4NjEwZWVhNDk0ZTkifQ.EXAD9MHfkO-LURfX3kqGyQ';

        var map = L.mapbox.map('map', 'mbiggins.md9k8mo8')
        .setView([38.8977, -77.0366], 16);

        map.scrollWheelZoom.disable();

        var myLocations = L.mapbox.featureLayer()
          .loadURL('/report.json')
          .addTo(map)

   

        // List take 2
        var markerList = document.getElementById('listings');

        myLocations.on('ready', function(e) {
            myLocations.eachLayer(function(layer) {
                var item = markerList.appendChild(document.createElement('div'));
                item.className = "item";
                var link = item.appendChild(document.createElement('a'));
                link.innerHTML = layer.toGeoJSON().properties.title + '<br >' + layer.toGeoJSON().properties.time_when;
                link.className = 'title';
                link.innerHTML += '<br /><small class="quiet">' + layer.toGeoJSON().properties.address + '</small>';
              
                item.onclick = function() {
                   map.setView(layer.getLatLng(), 16);
                   layer.openPopup();
                   setActive(item);
                };

                var popup = '<h3>'+layer.toGeoJSON().properties.title+'</h3><div>' + layer.toGeoJSON().properties.description;
                popup += '</div>';
                layer.bindPopup(popup);
            });
        });
        // List take 2

        // Clusters take 2
        // Since featureLayer is an asynchronous method, we use the `.on('ready'`
        // call to only use its marker data once we know it is actually loaded.
        myLocations.on('ready', function(e) {
            // The clusterGroup gets each marker in the group added to it
            // once loaded, and then is added to the map
            var clusterGroup = new L.MarkerClusterGroup();
            e.target.eachLayer(function(layer) {
                clusterGroup.addLayer(layer);
            });
            map.addLayer(clusterGroup);
        });
        // Clusters take 2


      // Search Bar Functionality & Locator
      map
        .addControl(L.mapbox.geocoderControl('mapbox.places'));
        L.control.locate().addTo(map);

      </script>
    </div>
  </div>
</section>
<!-- /Section: about -->
<!-- Section: services -->
<section id="service" class="home-section text-center">
  <div class="heading-about marginbot-50">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="section-heading">
            <h2>About</h2>
            <p>Samarit is a crowdsourced crime reporting platform. By allowing users to upload the type, 
            location and time of a crime incident, it generates hotspots so that fellow citizens 
            can take notice and be safe. </p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-md-4">
        <div class="service-box">
          <div class="service-icon">
            <i class="fa fa-street-view fa-4x"></i>
          </div>
          <div class="service-desc">
            <h5>Report</h5>
            <p>Don't stay silent. Be the first to report crime incidents around you to our 
            map-integrated database and take a step towards enhancing your neighborhood.</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-md-4">
        <div class="service-box">
          <div class="service-icon">
            <i class="fa fa-eye-slash fa-4x"></i>
          </div>
          <div class="service-desc">
            <h5>Be On The Lookout</h5>
            <p>See what is happening around you via the hotspots of Samarit. Know which roads to avoid, where to live and when to enhance your security.</p>
          </div>
        </div>
      </div>
      <div class="col-sm-4 col-md-4">
        <div class="service-box">
          <div class="service-icon">
            <i class="fa fa-heartbeat fa-4x"></i>
          </div>
          <div class="service-desc">
            <h5>Be Safe</h5>
            <p>Protect yourself and others around you from danger by being a good samaritan. Most importantly,stay safe.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /Section: services -->
<% end %>
<!-- /Section: works -->
<!-- Section: contact -->
<section id="contact" class="home-section text-center">
  <div class="heading-contact marginbot-50">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
          <div class="section-heading">
            <h2>Contact</h2>
            <p>Samarit was developed by a team of students for a final project at <a href = 'http://ixperience.co.za'>iXperience</a> in Cape Town, South Africa. For any questions or comments, please fill out the form below.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-offset-2">
        <div class="boxed-grey">
          <form id="contact-form">
            <div class="row">
              <div class="col-md-6">
                <div class="form-group">
                  <label for="name">
                  Name</label>
                  <input type="text" class="form-control" id="name" placeholder="Enter name" required="required" />
                </div>
                <div class="form-group">
                  <label for="email">
                  Email Address</label>
                  <div class="input-group">
                    <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span>
                    </span>
                    <input type="email" class="form-control" id="email" placeholder="Enter email" required="required" />
                  </div>
                </div>
                <div class="form-group">
                  <label for="subject">
                  Subject</label>
                  <select id="subject" name="subject" class="form-control" required="required">
                    <option value="na" selected="">Choose One:</option>
                    <option value="questions">General Questions</option>
                    <option value="suggestions">Suggestions</option>
                    <option value="support">Technical Support</option>
                  </select>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="name">
                  Message</label>
                  <textarea name="message" id="message" class="form-control" rows="9" cols="25" required="required"
                    placeholder="Message"></textarea>
                </div>
              </div>
              <div class="col-md-12">
                <button type="submit" class="btn btn-skin pull-right" id="btnContactUs">
                Send Message</button>
              </div>
            </div>
          </form>
        </div>
        <div class="widget-contact row">
          <div class="col-lg-6">
            <address>
              <strong>Samarit</strong><br>
              828 Brookwood Pl<br>
              Ann Arbor, MI 48104<br>
              <abbr title="Phone">P:</abbr> +1 (248) 225-4784
            </address>
          </div>
          <div class="col-lg-6">
            <address>
              <strong>Email</strong><br>
              <a href="mailto:kpinar@seas.upenn.edu">kpinar@seas.upenn.edu</a><br />
              <a href="mailto:matthew.w.biggins.1@nd.edu">matthew.w.biggins.1@nd.edu</a><br />
              <a href="mailto:aischwa@umich.edu">aischwa@umich.edu</a>
            </address>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- /Section: contact -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-12 col-lg-12">
      </div>
    </div>
  </div>
</footer>

app/views/report/new.html.erb
<div class="home-section text-center">
	<div class="report-form">
	<%= simple_form_for [current_user, @report], url: report_index_path do |f| %>
	  <%= f.input :report_type, collection: ["Arson","Assault","Disorderly Conduct","Drug","Harassment","Hate Crime","Homicide","Kidnapping","Sexual Assault","Shooting","Stabbing","Stalking","Theft","Vandalism"] %>
	  <br>
	  <%= f.input :address, placeholder: "123 Street City, State" %>
	  <br>
	  <%= f.input :description, as: :text, placeholder: "Details here..." %>
	  <br>
	  <%= f.input :time, collection: ["Just Now","15 Minutes Ago","30 Minutes Ago","45 Minutes Ago","1 Hour Ago","> 1 Hour Ago"], label: "When", default: ["Just Now"] %>
	  <br>
	  <%= f.button :submit, class: "btn btn-skin scroll" %>
	  <br>
	<% end %>
	<br>
	<%= link_to "Back", report_index_path, class: "btn btn-skin scroll" %>
	</div>
</div>

app/views/report/show.html.erb
<%= image_tag @report.avatar.url %>
<%= image_tag @report.avatar.url(:medium) %>
<%= image_tag @report.avatar.url(:thumb) %>

app/views/report/user_profile.html.erb
<div class="home-section text-center bg-gray">
	<h1>Profile</h1> 
		<div class = "row">
			<div class="col-md-4">
				<h2>
					<% i = 1 %>
					<% @reports.each do |r| %>
						<p><b><%= i %>. Incident: <%= r.report_type %></b></p>
						<p><%= r.address %></p>
						<p><%= r.time %></p>
						<p><%= r.description %></p>
						<%= link_to 'Edit Report', edit_report_path(r), class: "btn btn-skin scroll" %>
						<br>
						<br>
						<% i+= 1 %>
					<% end %>
				</h2>
			</div>
		</div>
</div>